name: Playwright CI Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright_tests:
    name: Run Playwright Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Check playwright-report contents before deploy
        if: always() # Ensures this step runs to give you info
        run: |
          echo "Current working directory: $(pwd)"
          echo "Workspace directory is: ${{ github.workspace }}"
          echo "--- Listing contents of ${{ github.workspace }} ---"
          ls -la ${{ github.workspace }}
          echo "--- Checking for playwright-report directory at: ${{ github.workspace }}/playwright-report ---"
          if [ -d "${{ github.workspace }}/playwright-report" ]; then
            echo "playwright-report directory FOUND."
            echo "--- Listing contents of ${{ github.workspace }}/playwright-report (ls -la) ---"
            ls -la ${{ github.workspace }}/playwright-report
            echo "--- Recursive listing of ${{ github.workspace }}/playwright-report (ls -laR) ---"
            ls -laR ${{ github.workspace }}/playwright-report
            echo "--- Checking specifically for index.html ---"
            if [ -f "${{ github.workspace }}/playwright-report/index.html" ]; then
              echo "playwright-report/index.html FOUND."
            else
              echo "playwright-report/index.html NOT FOUND."
            fi
          else
            echo "playwright-report directory NOT FOUND at ${{ github.workspace }}/playwright-report"
          fi

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Deploy report to GitHub Pages
        if: always() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
