name: Playwright CI Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright_tests:
    name: Run Playwright Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Publish Test Report Summary (Dorny)
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Playwright Test Results
          path: playwright-report/junit/junit-results.xml
          reporter: jest-junit

      - name: Upload Playwright report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-artifact
          path: playwright-report/html/
          retention-days: 7

      - name: Deploy HTML report to GitHub Pages
        if: always() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report/html

      - name: Add HTML Report link to Job Summary
        if: always() && steps.gh_pages_deploy.outcome == 'success'
        run: |
          echo "### Playwright HTML Report" >> $GITHUB_STEP_SUMMARY
          echo "View the full HTML report deployed to GitHub Pages:" >> $GITHUB_STEP_SUMMARY
          echo "[${{ steps.gh_pages_deploy.outputs.page_url }}](${{ steps.gh_pages_deploy.outputs.page_url }})" >> $GITHUB_STEP_SUMMARY
