name: Playwright CI Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright_tests:
    name: Run Playwright Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test

      - name: Mark workspace as safe for git commands
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Publish Test Report Summary (Dorny)
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Playwright Test Results
          path: playwright-report/junit/junit-results.xml
          reporter: jest-junit

      - name: Upload Playwright report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-artifact
          path: playwright-report/html/
          retention-days: 7

      - name: Deploy HTML report to GitHub Pages
        if: always() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report/html

      - name: Add HTML Report link to Job Summary
        if: always() && github.ref == 'refs/heads/main'
        run: |
          echo "### Playwright HTML Report" >> $GITHUB_STEP_SUMMARY
          echo "View the full HTML report deployed to GitHub Pages:" >> $GITHUB_STEP_SUMMARY
          echo "https://colonelcrackpot.github.io/spriteCloudAssessment/" >> $GITHUB_STEP_SUMMARY
